image: node:18 # Of een andere Node.js versie die je gebruikt

# Stages in de pipeline
stages:
  - build
  - deploy

# Job voor het bouwen van de app
build:
  stage: build
  script:
    - npm install
    - npm run build
    - mv dist public # Verplaats de buildbestanden naar de public map
  artifacts:
    paths:
      - public # Verzend de public map als artifact naar de volgende fase

# Job voor het deployen van de app naar GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - public # Deze map wordt door GitLab Pages gebruikt voor de deployment
  only:
    - branches # Deploy alleen op de main branch (je kan dit aanpassen naar jouw branch)