name: Deploy to GitHub Pages

# Run workflow when pushing to the main branch
on:
  push:
    branches:
      - main

# Define jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies and build the project
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:  ../../dist  # Dit moet de directory zijn waar je build wordt opgeslagen, bv. 'dist' voor Vite